project_id = "xwtmnzorzsvkamqemddk"

[functions.auth-email-hook]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.send-newsletter-welcome]
verify_jwt = false

[functions.ai-email-generate]
verify_jwt = true
